version: 2
jobs:
  build:
    docker:
      - image: marcosx/docker-builder:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile
      - setup_remote_docker
      - run:
          name: Build local image (local/rails-alpine)
          command: |
            docker build . -t local/rails-alpine
      - run:
          name: Scan the local image with trivy
          command: |
            trivy --clear-cache --no-progress --severity HIGH,CRITICAL local/rails-alpine

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

